config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "plans#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plans
  resources :performances
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_status.rb
class ClientStatus < ActiveHash::Base
  self.data = [
    { id: 1, name: '--'},
    { id: 2, name: '既存'},
    { id: 3, name: '新規'}
  ]

  include ActiveHash::Associations
  has_many :plans

end

app/models/performance.rb
class Performance < ApplicationRecord
  with_options presence: true do
    validates :goal,  format: { with: /\A[0-9]+\z/ }, numericality: true
  end

  belongs_to :user

end

app/models/plan.rb
class Plan < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :client
    validates :price, format: { with: /\A[0-9]+\z/ }, numericality: true
    validates :client_status_id, numericality: { other_than: 1 } 
    validates :sales_status_id,  numericality: { other_than: 1 } 
  end

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :client_status
  belongs_to :sales_status

end

app/models/sales_status.rb
class SalesStatus < ActiveHash::Base
  self.data = [
    { id: 1, name: '--'},
    { id: 2, name: '提案'},
    { id: 3, name: '受注'},
    { id: 4, name: '失注'}
  ]

  include ActiveHash::Associations
  has_many :plans
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    # validates :email,            uniqueness: { case_sensitive: false }
    validates :name              , format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/ }
    validates :employee_number,    format: { with:/\A[0-9]{4}+\z/}, uniqueness: true
  end

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, length: { minimum: 6 }

  has_many :plans
  has_one :performance

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :employee_number, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:employee_number])
    # binding.pry
  end
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_performance, only: [:edit, :update, :destroy]
  # before_action :login_state, only: [:edit, :destroy]


  def new
    @performance = Performance.new
  end

  def create
    @performance = Performance.new(performance_params)
    if @performance.save
      redirect_to "/users/#{current_user.id}"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @performance.update(performance_params)
      redirect_to "/users/#{current_user.id}"
    else
      render :edit
    end
  end

  private

  def performance_params
    params.require(:performance).permit(:goal).merge(user_id: current_user.id)
  end

  def set_performance
    @performance = Performance.find(params[:id])
  end

  # def login_state
  #   unless current_user.id == @performance.user_id
  #     redirect_to root_path
  #   end
  # end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :login_state, only: [:edit, :destroy]

  def index
    @plans = Plan.includes(:user).order("created_at DESC")

    @price = Plan.where(sales_status_id: 3)
    @price_sum = @price.sum(:price)

    if user_signed_in?
      @my_price = Plan.where(user: current_user.id, sales_status_id: 3)
      @my_price_sum = @my_price.sum(:price)
    end

    @knowledge =Plan.where.not(knowledge: '')
    
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @plan.update(plan_params)
      redirect_to plan_path
    else
      render :edit
    end
  end

  def destroy
    @plan.destroy
    redirect_to root_path
  end

  
  private

  def plan_params
    params.require(:plan).permit(:title, :client, :price, :client_status_id, :sales_status_id, :memo, :knowledge).merge(user_id: current_user.id)
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def login_state
    unless current_user.id == @plan.user_id
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :goal_set

  def show
    
    @goal = current_user.performance
    @plans = current_user.plans
    
    @my_price = Plan.where(user: current_user.id, sales_status_id: 3)
    @my_price_sum = @my_price.sum(:price)

    @performance = Performance.find(params[:id])

  end

  private
  def goal_set
    if current_user.performance.blank?
      redirect_to new_performance_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actions/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>初心者向けホームページテンプレート tp_beginner5</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" href="css/style.css">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>

<div id="container">

<header>
<nav id="menubar">
<ul>
  <% if user_signed_in? %>
    <li><%= link_to current_user.name, "#", class: "user-nickname" %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout" %></li>
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
  <% end %>
</ul>
</nav>

<h1 id="logo"><a href="index.html"><img src="images/logo.png" alt="SAMPLE SITE"></a></h1>
<aside id="mainimg"><img src="images/mainimg.jpg" alt=""></aside>
</header>

<%# <nav id="menubar">
<ul>
<li><a href="index.html">Home</a></li>
<li><a href="about.html">About</a></li>
<li><a href="gallery.html">Gallery</a></li>
<li><a href="link.html">Link</a></li>
</ul>
</nav> %>

<div id="contents">

<section id="new">
<h2>提案ネタ一覧</h2>
<dl>
<%# <dt>2019/04/22</dt>
<dd>より初心者が使いやすいよう少し調整。古いものを使っている人はそのままでOKです。</dd>
<dt>2017/10/06</dt>
<dd>初心者向け無料ホームページテンプレートtp_beginner5公開。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd>
<dt>20XX/00/00</dt>
<dd>サンプルテキスト。サンプルテキスト。サンプルテキスト。</dd> %>
</dl>
</section>

<section>

<h2>テンプレートのご利用前に必ずお読み下さい</h2>

<h3>利用規約のご案内</h3>
<p>このテンプレートは、<a href="https://template-party.com/">Template Party</a>にて無料配布している『初心者向けホームページテンプレート tp_beginner5』です。必ずダウンロード先のサイトの<a href="https://template-party.com/read.html">利用規約</a>をご一読の上でご利用下さい。</p>
<p><span class="color1">■<strong>HP最下部の著作表示『Web Design:Template-Party』は無断で削除しないで下さい。</strong></span><br>
わざと見えなく加工する事も禁止です。</p>
<p><span class="color1">■<strong>下部の著作を外したい場合は</strong></span><br>
<a href="https://template-party.com/">Template-Party</a>の<a href="https://template-party.com/member.html">ライセンス契約</a>を行う事でHP下部の著作を外す事ができます。</p>

<h3>当テンプレートの詳しい使い方は</h3>
<p><a href="about.html">こちらをご覧下さい。</a></p>

</section>

</div>
<!--/contents-->

<footer>
<small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

</div>
<!--/container-->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UricanApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/performances/edit.html.erb
<%= render "shared/header" %>

<div id="contents">

  <div class="items-sell-main">
    <h2 class="items-sell-title">目標の売上額を入力しよう</h2>
    <%= form_with model: @performance, url: performance_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="new-items">
      <div class="items-explain">
        <span class="sell-yen">¥</span>
        <%= f.text_field :goal, class:"price-input", id:"item-price", placeholder:"例）500000" %> 
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "保存する", class:"sell-btn" %>
      <%=link_to 'もどる', "/users/#{current_user.id}", class:"back-btn" %>
    </div>
    <% end %>
  </div>
</div>


<footer>
<small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

</div>

</body>
</html>

app/views/performances/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>初心者向けホームページテンプレート tp_beginner5</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" href="css/style.css">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>

<div id="container">

<header>
<div>
  <%= link_to 'urican_app', root_path, class:"menubar" %>
</div>

<nav id="menubar">
<ul>
  <% if user_signed_in? %>
    <li><%= link_to current_user.name, "#", class: "user-nickname" %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout" %></li>
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
  <% end %>
</ul>
</nav>

<%# <nav id="menubar">
<ul>
<li><a href="index.html">Home</a></li>
<li><a href="about.html">About</a></li>
<li><a href="gallery.html">Gallery</a></li>
<li><a href="link.html">Link</a></li>
</ul>
</nav> %>

<div id="contents">

<h2>売上状況</h2>
<%= link_to '目標を入力する', new_performance_path %>
<div>目標<%= @goal %>円</div>

</div>
<!--/contents-->

<footer>
<small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

</div>
<!--/container-->

</body>
</html>

app/views/performances/new.html.erb
<%= render "shared/header" %>

<div id="contents">

  <div class="items-sell-main">
    <h2 class="items-sell-title">目標の売上額を入力しよう</h2>
    <%= form_with model: @performance, url: performances_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="new-items">
      <div class="items-explain">
        <span class="sell-yen">¥</span>
        <%= f.text_field :goal, class:"price-input", id:"item-price", placeholder:"例）500000" %> 
      </div>
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "保存する", class:"sell-btn" %>
      <%=link_to 'もどる', "/users/#{current_user.id}", class:"back-btn" %>
    </div>
    <% end %>
  </div>
</div>

<footer>
</footer>

</div>

</body>
</html>

app/views/performances/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>初心者向けホームページテンプレート tp_beginner5</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="ここにサイト説明を入れます">
<meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
<link rel="stylesheet" href="css/style.css">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>

<div id="container">

<header>
<div>
  <%= link_to 'urican_app', root_path, class:"menubar" %>
</div>

<nav id="menubar">
<ul>
  <% if user_signed_in? %>
    <li><%= link_to current_user.name, "#", class: "user-nickname" %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout" %></li>
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
  <% end %>
</ul>
</nav>

<%# <nav id="menubar">
<ul>
<li><a href="index.html">Home</a></li>
<li><a href="about.html">About</a></li>
<li><a href="gallery.html">Gallery</a></li>
<li><a href="link.html">Link</a></li>
</ul>
</nav> %>

<div id="contents">

<h2>売上状況</h2>
<%= link_to '目標を入力する', new_performance_path %>
<div>目標<%= @goal %>円</div>

</div>
<!--/contents-->

<footer>
<small>Copyright&copy; <a href="index.html">SAMPLE SITE</a> All Rights Reserved.</small>
<span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
</footer>

</div>
<!--/container-->

</body>
</html>

app/views/plans/edit.html.erb
<%= render "shared/header" %>

<div id="contents">

  <div class="items-sell-main">
    <h2 class="items-sell-title">提案の情報を入力</h2>
    <%= form_with model: @plan, url: plan_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="new-items">
      <div class="weight-bold-text">
        提案名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :title, class:"items-text", id:"item-name", placeholder:"提案内容を記入してください", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          顧客名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :client, class:"items-text", id:"item-info", placeholder:"例：株式会社〇〇" ,maxlength:"40" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          提案金額
          <span class="indispensable">必須</span>
        </div>
        <span class="sell-yen">¥</span>
         <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）500000" %>          </div>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text"></div>
      <div class="form">
        <div class="weight-bold-text">
          顧客ステータス
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:client_status_id, ClientStatus.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          提案ステータス
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sales_status_id, SalesStatus.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        提案メモ
      <%= f.text_area :memo, class:"items-text", id:"item-name", placeholder:"提案内容・状況・備考など", maxlength:"150" %>
      </div>
      <div class="weight-bold-text">
        ナレッジ
        <%= f.text_area :knowledge, class:"items-text", id:"item-info", placeholder:"共有したいことがあれば記載しましょう。例)工夫したこと、業界の情報、お客様の反応など" ,maxlength:"150" %>
      </div>
      
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "変更する", class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

<footer>
</footer>

</div>

</body>
</html>

app/views/plans/index.html.erb
<%= render "shared/header" %>

<div id="contents">
<h2>現在の売上</h2>
<% if user_signed_in? %>
  <canvas id="myChart" width="60％" height="20%" ></canvas>
  <script>
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      datasets: [{
        label: '全体実績',
        data: [<%= @price_sum %>],
        backgroundColor: "rgba(130,201,169,0.5)"
    },{
        label: '個人実績',
        data: [<%= @my_price_sum %>],
        backgroundColor: "rgba(219,39,91,0.5)"
    }]
   },
   options: {
     scales: {
       yAxes: [{
         ticks: {
           beginAtZero: true
         }
       }]
     }
   }
  });
  </script>

  全体：<%= @price_sum %>円 ／個人：<%= @my_price_sum %>円
<% else %>
  <div>確認するにはログインが必要です！</div>
<% end %>

<section id="new">
<h2>プラン一覧</h2>
  <%= link_to '新規投稿', new_plan_path %>

  <ul class='item-lists'>
    <h3 class='item-name'>
      <div class='plan-name'>提案プラン</div>
      <div class='plan-name'>顧客名</div>
      <div class='plan-name'>顧客ステータス</div>
      <div class='plan-name'>金額</div>
      <div class='plan-name'>受注ステータス</div>
      <div class='plan-name'>担当</div>
    </h3>

  <% if user_signed_in? %>
      <% @plans.each do |plan| %>
          <%=link_to plan_path(plan) do %>
            <h3 class='item-name'>
              <div><%= plan.title %></div>
              <div><%= plan.client %></div>
              <div><%= plan.client_status.name %></div>
              <div><%= plan.price %>円</div>
              <div><%= plan.sales_status.name %></div>
              <div><%= plan.user.name %></div>
            </h3>
          <% end %>
      <% end %>
  <% end %>

</section>

<h2>ナレッジ一覧</h2>

<ul class='item-lists'>
  <h3 class='item-name'>
    <div class='plan-name'>顧客名</div>
    <div class='plan-name'>投稿者</div>
    <div class='plan-name'>ナレッジ内容</div>
  </h3>

  <% @knowledge.each do |knowledge| %>
      <%=link_to plan_path(knowledge) do %>
      <h3 class='item-name'>
        <div><%= knowledge.client %></div>
        <div><%= knowledge.user.name %></div>
        <div><%= knowledge.knowledge %></div>
      </h3>
      <% end %>
  <% end %>

</div>

<footer>
</footer>

</div>

</body>
</html>

app/views/plans/new.html.erb
<%= render "shared/header" %>

<div id="contents">

  <div class="items-sell-main">
    <h2 class="items-sell-title">提案の情報を入力</h2>
    <%= form_with model: @plan, url: plans_path, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="new-items">
      <div class="weight-bold-text">
        提案名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :title, class:"items-text", id:"item-name", placeholder:"提案内容を記入してください", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          顧客名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :client, class:"items-text", id:"item-info", placeholder:"例：株式会社〇〇" ,maxlength:"40" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          提案金額
          <span class="indispensable">必須</span>
        </div>
        <span class="sell-yen">¥</span>
         <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）500000" %>          </div>
      </div>
    </div>

    <div class="items-detail">
      <div class="weight-bold-text"></div>
      <div class="form">
        <div class="weight-bold-text">
          顧客ステータス
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:client_status_id, ClientStatus.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          提案ステータス
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:sales_status_id, SalesStatus.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        提案メモ
      <%= f.text_area :memo, class:"items-text", id:"item-name", placeholder:"提案内容・状況・備考など", maxlength:"150" %>
      </div>
      <div class="weight-bold-text">
        ナレッジ
        <%= f.text_area :knowledge, class:"items-text", id:"item-info", placeholder:"共有したいことがあれば記載しましょう。例)工夫したこと、業界の情報、お客様の反応など" ,maxlength:"150" %>
      </div>
      
    </div>

    <div class="sell-btn-contents">
      <%= f.submit "保存する", class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>


<footer>
</footer>

</div>

</body>
</html>

app/views/plans/show.html.erb
<%= render "shared/header" %>

  <div id="contents">
    <h2>提案プラン</h2>
      <div class="detail-table">          
            <div class="detail-item" >提案プラン</div>
            <div class="detail-value"><%= @plan.title %></div>
      </div>
      <div class="detail-table">
            <div class="detail-item">顧客名</div>
            <div class="detail-value"><%= @plan.client %></div>
      </div>
      <div class="detail-table">
            <div class="detail-item">顧客ステータス</div>
            <div class="detail-value"><%= @plan.client_status.name %></div>
      </div>
      <div class="detail-table">
            <div class="detail-item">金額</div>
            <div class="detail-value"><%= @plan.price %>円</div>
      </div>
      <div class="detail-table">
            <div class="detail-item">受注ステータス</div>
            <div class="detail-value"><%= @plan.sales_status.name  %></div>
      </div>
      <div class="detail-table">
            <div class="detail-item">担当</div>
            <div class="detail-value"><%= @plan.user.name %></div>
      </div>
      <div class="detail-table">
            <div class="detail-item">メモ</div>
            <div class="detail-value"><%= @plan.memo %></div>
       </div>
      <div class="detail-table">
           <div class="detail-item">ナレッジ</div>
            <div class="detail-value"><%= @plan.knowledge %></div>
      </div>
      <% if user_signed_in?%>
        <% if current_user.id == @plan.user_id %>
          <%= link_to '編集', edit_plan_path(@plan.id), class: "item-red-btn" %>
          <%= link_to '削除', plan_path(@plan.id), method: :delete, class:'item-destroy' %>
        <% end %>
      <% end %>
  </div>
</div>

<footer>
</footer>

</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div id="contents">

<h2>あなたの売上</h2>

  <canvas id="myChart" width="60％" height="20%" ></canvas>
  <script>
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      datasets: [{
        label: '目標',
        data: [<%= @goal.goal %>],
        backgroundColor: "rgba(130,201,169,0.5)"
    },{
        label: '実績',
        data: [<%= @my_price_sum %>],
        backgroundColor: "rgba(219,39,91,0.5)"
    }]
   },
   options: {
     scales: {
       yAxes: [{
         ticks: {
           beginAtZero: true
         }
       }]
     }
   }
  });
  </script>

  <div>個人目標：<%= @goal.goal %>円 ／受注実績：<%= @my_price_sum %>円</div>
  <div>達成まで：<%= @goal.goal.to_i - @my_price_sum.to_i %>円</div>

  目標を<%= link_to '修正', edit_performance_path %>



<h2>プラン一覧</h2>
  <%= link_to '新規投稿', new_plan_path %>

    <h3 class='item-name'>
      <div class='plan-name'>提案プラン</div>
      <div class='plan-name'>顧客名</div>
      <div class='plan-name'>顧客ステータス</div>
      <div class='plan-name'>金額</div>
      <div class='plan-name'>受注ステータス</div>
    </h3>

 <% @plans.each do |plan| %>
    <%=link_to plan_path(plan) do %>
      <h3 class='item-name'>
        <div><%= plan.title %></div>
        <div><%= plan.client %></div>
        <div><%= plan.client_status.name %></div>
        <div><%= plan.price %>円</div>
        <div><%= plan.sales_status.name %></div>
      </h3>
    <% end %>
  <% end %>
</div>

<footer>
</footer>
</div>

</body>
</html>